export const MOVIES = [
  {
    id: 1,
    title: "Yulduzlar Sardori",
    poster: "https://picsum.photos/seed/cinemahub-1/500/750",
    genres: ["Fantastika", "Jangari"],
    year: 2023,
    duration: 142,
    country: "O'zbekiston",
    director: "Ali Rahimov",
    actors: ["Sardor Mirzayev", "Nilufar Xonova", "Bekzod Yusupov"],
    rating: 8.6,
    description:
      "Galaktika chetidagi koloniya dushman flotidan qutqarilishi uchun yosh serkarda o'z jamoasini so'nggi jangga boshlaydi.",
  },
  {
    id: 2,
    title: "Kulgu Terapiyasi",
    poster: "https://picsum.photos/seed/cinemahub-2/500/750",
    genres: ["Komediya"],
    year: 2021,
    duration: 104,
    country: "AQSH",
    director: "Marko Diaz",
    actors: ["Jeyms Karter", "Amanda Fill", "Tomas Grey"],
    rating: 7.2,
    description:
      "Ishdan bo'shatilgan psixolog o'zining eng g'alati mijozlari yordamida hayotga qaytadan qiziqish uyg'otadi.",
  },
  {
    id: 3,
    title: "Jimjit Bog'",
    poster: "https://picsum.photos/seed/cinemahub-3/500/750",
    genres: ["Drama"],
    year: 2020,
    duration: 128,
    country: "Yaponiya",
    director: "Amara Ito",
    actors: ["Haruki Sato", "Yuna Kobayashi", "Ren Tanaka"],
    rating: 8.9,
    description:
      "Uch aka-uka otalari vafotidan so'ng oilaviy fermaga qaytib, yillar davomida yashirilgan sirlarga duch keladi.",
  },
  {
    id: 4,
    title: "Neon Zarba",
    poster: "https://picsum.photos/seed/cinemahub-4/500/750",
    genres: ["Jangari", "Triller"],
    year: 2022,
    duration: 118,
    country: "Buyuk Britaniya",
    director: "Jeks Reyli",
    actors: ["Diana Kross", "Omar Fayzullayev", "Lea Marten"],
    rating: 7.8,
    description:
      "Sobiq xaker o'tmishidagi jinoiy tarmoq tomonidan so'nggi bir ishga majburlanadi va bu uning hayotini tubdan o'zgartiradi.",
  },
  {
    id: 5,
    title: "Sokin O'rmon Sirlari",
    poster: "https://picsum.photos/seed/cinemahub-5/500/750",
    genres: ["Qo'rqinchli", "Triller"],
    year: 2018,
    duration: 97,
    country: "Kanada",
    director: "Greys Xollovey",
    actors: ["Emili Stoun", "Rayan Kolt", "Karter Vayt"],
    rating: 6.9,
    description:
      "Oilaviy dam olish uyida o'tkazilgan tinch hafta yovvoyi tabiat sirlari tufayli omon qolish uchun kurashga aylanadi.",
  },
  {
    id: 6,
    title: "Qog'oz Yuraklar",
    poster: "https://picsum.photos/seed/cinemahub-6/500/750",
    genres: ["Romantik", "Komediya"],
    year: 2023,
    duration: 109,
    country: "Fransiya",
    director: "Noa Bennet",
    actors: ["Klara Dyubua", "Anton Moro", "Iman Petit"],
    rating: 7.5,
    description:
      "Bir-birini shaxsan tanimagan holda yozishmalar orqali yaqinlashgan ikki raqib nihoyat yuzma-yuz kelganda hammasi o'zgaradi.",
  },
  {
    id: 7,
    title: "Shisha Labirint",
    poster: "https://picsum.photos/seed/cinemahub-7/500/750",
    genres: ["Triller", "Jinoiy"],
    year: 2021,
    duration: 131,
    country: "Hindiston",
    director: "Priya Nair",
    actors: ["Priya Nair", "Arjun Kapur", "Rohit Sharma"],
    rating: 8.2,
    description:
      "Tergovchi ayol o'zi ovlayotgan qotilning ongi ichida qopqonga tushib qoladi va haqiqatni topish uchun aqliy o'yinga kirishadi.",
  },
  {
    id: 8,
    title: "Ajdar Qo'ynog'i",
    poster: "https://picsum.photos/seed/cinemahub-8/500/750",
    genres: ["Fantastika", "Sarguzasht"],
    year: 2017,
    duration: 136,
    country: "Yangi Zelandiya",
    director: "Yuan Ferauzer",
    actors: ["Sofi Larkin", "Devid Xolt", "Mira Kessler"],
    rating: 8.0,
    description:
      "Yetim temirchi qiz o'zining ajdarlar sehrining so'nggi vorisi ekanini bilib qoladi va qadimiy kuchni himoya qilishga chog'lanadi.",
  },
  {
    id: 9,
    title: "Okean Nafasi",
    poster: "https://picsum.photos/seed/cinemahub-9/500/750",
    genres: ["Hujjatli"],
    year: 2020,
    duration: 88,
    country: "Avstraliya",
    director: "Sofiya Markketti",
    actors: ["Ovozli hikoyachi: Devid Attenboro uslubida"],
    rating: 8.6,
    description:
      "Dunyo bo'ylab yo'qolib borayotgan marjon riflari va ular ichidagi hayotni yaqindan ko'rsatuvchi chuqur suvosti safari.",
  },
  {
    id: 10,
    title: "Kichik Qirolliklar",
    poster: "https://picsum.photos/seed/cinemahub-10/500/750",
    genres: ["Animatsiya", "Komediya"],
    year: 2022,
    duration: 95,
    country: "O'zbekiston",
    director: "Ren Vatanabe",
    actors: ["Ovoz: Diyor Mahmudov", "Ovoz: Sabina Yo'ldosheva"],
    rating: 8.3,
    description:
      "Unutilgan bog'da chumolilar koloniyasi o'z kichik imperiyasini qurar ekan, kulgili va iliq sarguzashtlar boshlanadi.",
  },
];
